### ISSUE TITLE
category page 404

### ISSUE THREAD

**Issue by ComplicatedPhenomenon** [agusmakmun/agusmakmun.github.io#30]
Hi, @agusmakmun, thanks for your great work. 

I customized your template a long time ago. [https://czfzdxx.gitlab.io](https://czfzdxx.gitlab.io)
Recently I suddenly find out that my category page can't be displayed, which has no problem in local test
<img width="910" alt="screenshot 2019-01-02 at 11 40 57" src="https://user-images.githubusercontent.com/24690806/50579840-aef04f80-0e83-11e9-89aa-998fbad9d36a.png">

Now I cannot find where I modified was wrong

Below is  `_config.yml`
```yml
title: Raw Thought
author: CZFZDXX
about: Practice your creativity
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []


social:
    - icon: fa-twitter
      link: "https://twitter.com/czfzdxx"
    - icon: fa-stack-overflow
      link: "https://stackoverflow.com/users/7583919/complicatedphenomenon"
    - icon: fa-gitlab
      link: "https://gitlab.com/complicatedphenomenon"

share:
  twitter_username: czfzdxx

urls:
    - text: About
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://czfzdxx.gitlab.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
```
