### ISSUE TITLE
turning off code block wrapping

### ISSUE THREAD

**Issue by le91688** [agusmakmun/agusmakmun.github.io#9]
Cannot figure out how to get code block wrapping turned off.
Any help would be greatly appreciated!

**Comment by agusmakmun** [comment]
This because bootstrap using `word-break: break-all; word-wrap: break-word;` for `pre` element. 
I think you can handle it using css;

```css
pre {
    word-break: normal;
    word-wrap: normal;
}
```
